#!/usr/bin/env ruby
# frozen_string_literal: true

require "rubocop-kata"
require "rubocop/kata/checkup"
require "rubocop/kata/plan"
require "rubocop/kata/kit"

COMMANDS = { "doctor" => RuboCop::Kata::Checkup, "plan" => RuboCop::Kata::Plan, "skill" => RuboCop::Kata::Kit }.freeze

command = COMMANDS[ARGV.first]
abort("usage: rubocop-kata #{COMMANDS.keys.join("|")} [path]") if command.nil?

exit(command.new(ARGV.fetch(1, Dir.pwd)).run)
